/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void __attribute__((weak)) setting_timing_custom_load_start(void) {
}
void __attribute__((weak)) setting_timing_custom_unload_start(void) {
}

static void setting_timing_unload_start (lv_event_t *e) {
    setting_timing_custom_unload_start();
}

static void setting_timing_load_start (lv_event_t *e) {
    setting_timing_custom_load_start();
}

void __attribute__((weak)) setting_timing_cancel_cont_custom_clicked(void) {
}

static void setting_timing_cancel_cont_clicked (lv_event_t *e) {
    setting_timing_cancel_cont_custom_clicked();
}

void __attribute__((weak)) setting_timing_confirm_cont_custom_clicked(void) {
}

static void setting_timing_confirm_cont_clicked (lv_event_t *e) {
    setting_timing_confirm_cont_custom_clicked();
}


void setting_timing_create(ui_manager_t *ui)
{
    setting_timing_t *scr = setting_timing_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, setting_timing_unload_start, LV_EVENT_SCREEN_UNLOAD_START, NULL);
    lv_obj_add_event_cb(scr->obj, setting_timing_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->roller_minute
    scr->roller_minute = lv_roller_create(scr->obj);
    lv_roller_set_options(scr->roller_minute, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_visible_row_count(scr->roller_minute, 10);
    lv_obj_set_pos(scr->roller_minute, 683, 0);
    lv_obj_set_size(scr->roller_minute, 300, 744);

    // Set style of scr->roller_minute
    lv_obj_set_style_bg_opa(scr->roller_minute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_minute, fs_fzltxhjw_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_minute, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->roller_minute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->roller_minute, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_minute, fs_fzltxhjw_80, LV_PART_SELECTED | LV_STATE_DEFAULT);

    // Init scr->cancel_cont
    scr->cancel_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cancel_cont, 0, 0);
    lv_obj_set_size(scr->cancel_cont, 200, 720);
    lv_obj_set_scrollbar_mode(scr->cancel_cont, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->cancel_cont, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->cancel_cont
    lv_obj_set_style_bg_color(scr->cancel_cont, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cancel_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cancel_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cancel_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cancel_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cancel_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cancel_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cancel_cont
    lv_obj_add_event_cb(scr->cancel_cont, setting_timing_cancel_cont_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->cancel_cont);
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_style_img_opa(scr->image_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_1, 46, 310);
    lv_obj_add_flag(scr->image_1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_1, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_1, "H");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 218, 335);
    lv_obj_set_size(scr->label_1, 50, 50);

    // Set style of scr->label_1
    lv_obj_set_style_text_font(scr->label_1, fs_fzltxhjw_50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_2, ":");
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 615, 320);
    lv_obj_set_size(scr->label_2, 50, 100);

    // Set style of scr->label_2
    lv_obj_set_style_text_font(scr->label_2, fs_fzltxhjw_80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->confirm_cont
    scr->confirm_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->confirm_cont, 1080, 0);
    lv_obj_set_size(scr->confirm_cont, 200, 720);
    lv_obj_set_scrollbar_mode(scr->confirm_cont, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->confirm_cont, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->confirm_cont
    lv_obj_set_style_bg_color(scr->confirm_cont, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->confirm_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->confirm_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->confirm_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->confirm_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->confirm_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->confirm_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->confirm_cont
    lv_obj_add_event_cb(scr->confirm_cont, setting_timing_confirm_cont_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->confirm_cont);
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_style_img_opa(scr->image_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_2, 46, 310);
    lv_obj_add_flag(scr->image_2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_2, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_3, "M");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 1008, 335);
    lv_obj_set_size(scr->label_3, 50, 50);

    // Set style of scr->label_3
    lv_obj_set_style_text_font(scr->label_3, fs_fzltxhjw_50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->roller_hour
    scr->roller_hour = lv_roller_create(scr->obj);
    lv_roller_set_options(scr->roller_hour, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60\n61\n62\n63\n64\n65\n66\n67\n68\n69\n70\n71\n72\n73\n74\n75\n76\n77\n78\n79\n80\n81\n82\n83\n84\n85\n86\n87\n88\n89\n90\n91\n92\n93\n94\n95\n96\n97\n98\n99", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_visible_row_count(scr->roller_hour, 10);
    lv_obj_set_pos(scr->roller_hour, 304, 0);
    lv_obj_set_size(scr->roller_hour, 300, 744);

    // Set style of scr->roller_hour
    lv_obj_set_style_bg_opa(scr->roller_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_hour, fs_fzltxhjw_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_hour, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->roller_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->roller_hour, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_hour, fs_fzltxhjw_80, LV_PART_SELECTED | LV_STATE_DEFAULT);


}
