/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void __attribute__((weak)) about_screen_custom_created(void) {
}

void __attribute__((weak)) about_screen_about_back_custom_clicked(void) {
}

static void about_screen_about_back_clicked (lv_event_t *e) {
    about_screen_about_back_custom_clicked();
}


void about_screen_create(ui_manager_t *ui)
{
    about_screen_t *scr = about_screen_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->about_text
    scr->about_text = lv_label_create(scr->obj);
    lv_label_set_text(scr->about_text, "");
    lv_label_set_long_mode(scr->about_text, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->about_text, 160, 160);
    lv_obj_set_size(scr->about_text, 868, 466);

    // Set style of scr->about_text
    lv_obj_set_style_text_font(scr->about_text, fs_fzltxhjw_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->about_text, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->about_text, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->about_back
    scr->about_back = lv_img_create(scr->obj);
    lv_img_set_src(scr->about_back, LVGL_IMAGE_PATH(back_135x135.png));
    lv_img_set_pivot(scr->about_back, 50, 50);
    lv_img_set_angle(scr->about_back, 0);
    lv_obj_set_style_img_opa(scr->about_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->about_back, 22, 22);
    lv_obj_add_flag(scr->about_back, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->about_back
    lv_obj_add_event_cb(scr->about_back, about_screen_about_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_45
    scr->label_45 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_45, "About");
    lv_label_set_long_mode(scr->label_45, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_45, 168, 28);
    lv_obj_set_size(scr->label_45, 750, 117);

    // Set style of scr->label_45
    lv_obj_set_style_text_font(scr->label_45, fs_fzltxhjw_95, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_45, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    about_screen_custom_created();
}
