/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void __attribute__((weak)) cook_screen_cook5_img_custom_clicked(void) {
}

static void cook_screen_cook5_img_clicked (lv_event_t *e) {
    cook_screen_cook5_img_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook4_img_custom_clicked(void) {
}

static void cook_screen_cook4_img_clicked (lv_event_t *e) {
    cook_screen_cook4_img_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook3_img_custom_clicked(void) {
}

static void cook_screen_cook3_img_clicked (lv_event_t *e) {
    cook_screen_cook3_img_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook2_img_custom_clicked(void) {
}

static void cook_screen_cook2_img_clicked (lv_event_t *e) {
    cook_screen_cook2_img_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook1_img_custom_clicked(void) {
}

static void cook_screen_cook1_img_clicked (lv_event_t *e) {
    cook_screen_cook1_img_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook1_label_custom_clicked(void) {
}

static void cook_screen_cook1_label_clicked (lv_event_t *e) {
    cook_screen_cook1_label_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook2_label_custom_clicked(void) {
}

static void cook_screen_cook2_label_clicked (lv_event_t *e) {
    cook_screen_cook2_label_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook3_label_custom_clicked(void) {
}

static void cook_screen_cook3_label_clicked (lv_event_t *e) {
    cook_screen_cook3_label_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook4_label_custom_clicked(void) {
}

static void cook_screen_cook4_label_clicked (lv_event_t *e) {
    cook_screen_cook4_label_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook5_label_custom_clicked(void) {
}

static void cook_screen_cook5_label_clicked (lv_event_t *e) {
    cook_screen_cook5_label_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook6_img_custom_clicked(void) {
}

static void cook_screen_cook6_img_clicked (lv_event_t *e) {
    cook_screen_cook6_img_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook6_label_custom_clicked(void) {
}

static void cook_screen_cook6_label_clicked (lv_event_t *e) {
    cook_screen_cook6_label_custom_clicked();
}

void __attribute__((weak)) cook_screen_cook_back_custom_clicked(void) {
}

static void cook_screen_cook_back_clicked (lv_event_t *e) {
    cook_screen_cook_back_custom_clicked();
}


void cook_screen_create(ui_manager_t *ui)
{
    cook_screen_t *scr = cook_screen_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cook_cont
    scr->cook_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cook_cont, 20, 170);
    lv_obj_set_size(scr->cook_cont, 1240, 520);
    lv_obj_set_scrollbar_mode(scr->cook_cont, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->cook_cont, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(scr->cook_cont, LV_OBJ_FLAG_SCROLL_CHAIN_HOR);

    // Set style of scr->cook_cont
    lv_obj_set_style_bg_color(scr->cook_cont, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->cook_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cook_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cook_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cook_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cook_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cook_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cook_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cook5_img
    scr->cook5_img = lv_img_create(scr->cook_cont);
    lv_img_set_src(scr->cook5_img, LVGL_IMAGE_PATH(omelette_455x520.png));
    lv_img_set_pivot(scr->cook5_img, 50, 50);
    lv_img_set_angle(scr->cook5_img, 0);
    lv_obj_set_style_img_opa(scr->cook5_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->cook5_img, 1820, 0);
    lv_obj_add_flag(scr->cook5_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->cook5_img
    lv_obj_add_event_cb(scr->cook5_img, cook_screen_cook5_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook4_img
    scr->cook4_img = lv_img_create(scr->cook_cont);
    lv_img_set_src(scr->cook4_img, LVGL_IMAGE_PATH(chips_455x520.png));
    lv_img_set_pivot(scr->cook4_img, 50, 50);
    lv_img_set_angle(scr->cook4_img, 0);
    lv_obj_set_style_img_opa(scr->cook4_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->cook4_img, 1365, 0);
    lv_obj_add_flag(scr->cook4_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->cook4_img
    lv_obj_add_event_cb(scr->cook4_img, cook_screen_cook4_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook3_img
    scr->cook3_img = lv_img_create(scr->cook_cont);
    lv_img_set_src(scr->cook3_img, LVGL_IMAGE_PATH(chocolate_455x520.png));
    lv_img_set_pivot(scr->cook3_img, 50, 50);
    lv_img_set_angle(scr->cook3_img, 0);
    lv_obj_set_style_img_opa(scr->cook3_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->cook3_img, 910, 0);
    lv_obj_add_flag(scr->cook3_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->cook3_img
    lv_obj_add_event_cb(scr->cook3_img, cook_screen_cook3_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook2_img
    scr->cook2_img = lv_img_create(scr->cook_cont);
    lv_img_set_src(scr->cook2_img, LVGL_IMAGE_PATH(pancake_455x520.png));
    lv_img_set_pivot(scr->cook2_img, 50, 50);
    lv_img_set_angle(scr->cook2_img, 0);
    lv_obj_set_style_img_opa(scr->cook2_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->cook2_img, 455, 0);
    lv_obj_add_flag(scr->cook2_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->cook2_img
    lv_obj_add_event_cb(scr->cook2_img, cook_screen_cook2_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook1_img
    scr->cook1_img = lv_img_create(scr->cook_cont);
    lv_img_set_src(scr->cook1_img, LVGL_IMAGE_PATH(beef_455x520.png));
    lv_img_set_pivot(scr->cook1_img, 50, 50);
    lv_img_set_angle(scr->cook1_img, 0);
    lv_obj_set_style_img_opa(scr->cook1_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->cook1_img, 0, 0);
    lv_obj_add_flag(scr->cook1_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->cook1_img
    lv_obj_add_event_cb(scr->cook1_img, cook_screen_cook1_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook1_label
    scr->cook1_label = lv_label_create(scr->cook_cont);
    lv_label_set_text(scr->cook1_label, "Steak");
    lv_label_set_long_mode(scr->cook1_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cook1_label, 16, 433);
    lv_obj_set_size(scr->cook1_label, 228, 69);
    lv_obj_add_flag(scr->cook1_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->cook1_label
    lv_obj_set_style_text_font(scr->cook1_label, fs_fzltxhjw_70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cook1_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(scr->cook1_label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cook1_label
    lv_obj_add_event_cb(scr->cook1_label, cook_screen_cook1_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook2_label
    scr->cook2_label = lv_label_create(scr->cook_cont);
    lv_label_set_text(scr->cook2_label, "Pancake");
    lv_label_set_long_mode(scr->cook2_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cook2_label, 471, 433);
    lv_obj_set_size(scr->cook2_label, 328, 69);
    lv_obj_add_flag(scr->cook2_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->cook2_label
    lv_obj_set_style_text_font(scr->cook2_label, fs_fzltxhjw_70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cook2_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(scr->cook2_label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cook2_label
    lv_obj_add_event_cb(scr->cook2_label, cook_screen_cook2_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook3_label
    scr->cook3_label = lv_label_create(scr->cook_cont);
    lv_label_set_text(scr->cook3_label, "Melting\nChocolate");
    lv_label_set_long_mode(scr->cook3_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cook3_label, 926, 350);
    lv_obj_set_size(scr->cook3_label, 363, 162);
    lv_obj_add_flag(scr->cook3_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->cook3_label
    lv_obj_set_style_text_font(scr->cook3_label, fs_fzltxhjw_70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cook3_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(scr->cook3_label, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cook3_label
    lv_obj_add_event_cb(scr->cook3_label, cook_screen_cook3_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook4_label
    scr->cook4_label = lv_label_create(scr->cook_cont);
    lv_label_set_text(scr->cook4_label, "Chips");
    lv_label_set_long_mode(scr->cook4_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cook4_label, 1381, 433);
    lv_obj_set_size(scr->cook4_label, 328, 69);
    lv_obj_add_flag(scr->cook4_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->cook4_label
    lv_obj_set_style_text_font(scr->cook4_label, fs_fzltxhjw_70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cook4_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(scr->cook4_label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cook4_label
    lv_obj_add_event_cb(scr->cook4_label, cook_screen_cook4_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook5_label
    scr->cook5_label = lv_label_create(scr->cook_cont);
    lv_label_set_text(scr->cook5_label, "Omelette");
    lv_label_set_long_mode(scr->cook5_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cook5_label, 1836, 433);
    lv_obj_set_size(scr->cook5_label, 328, 69);
    lv_obj_add_flag(scr->cook5_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->cook5_label
    lv_obj_set_style_text_font(scr->cook5_label, fs_fzltxhjw_70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cook5_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(scr->cook5_label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cook5_label
    lv_obj_add_event_cb(scr->cook5_label, cook_screen_cook5_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook6_img
    scr->cook6_img = lv_img_create(scr->cook_cont);
    lv_img_set_src(scr->cook6_img, LVGL_IMAGE_PATH(popcorn_455x520.png));
    lv_img_set_pivot(scr->cook6_img, 50, 50);
    lv_img_set_angle(scr->cook6_img, 0);
    lv_obj_set_style_img_opa(scr->cook6_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->cook6_img, 2265, 0);
    lv_obj_add_flag(scr->cook6_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->cook6_img
    lv_obj_add_event_cb(scr->cook6_img, cook_screen_cook6_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook6_label
    scr->cook6_label = lv_label_create(scr->cook_cont);
    lv_label_set_text(scr->cook6_label, "Popcorn");
    lv_label_set_long_mode(scr->cook6_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cook6_label, 2281, 433);
    lv_obj_set_size(scr->cook6_label, 328, 69);
    lv_obj_add_flag(scr->cook6_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->cook6_label
    lv_obj_set_style_text_font(scr->cook6_label, fs_fzltxhjw_70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cook6_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(scr->cook6_label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cook6_label
    lv_obj_add_event_cb(scr->cook6_label, cook_screen_cook6_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->cook_back
    scr->cook_back = lv_img_create(scr->obj);
    lv_img_set_src(scr->cook_back, LVGL_IMAGE_PATH(back_135x135.png));
    lv_img_set_pivot(scr->cook_back, 50, 50);
    lv_img_set_angle(scr->cook_back, 0);
    lv_obj_set_style_img_opa(scr->cook_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->cook_back, 22, 22);
    lv_obj_add_flag(scr->cook_back, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(scr->cook_back, LV_OBJ_FLAG_SCROLLABLE);

    // Set event handler of scr->cook_back
    lv_obj_add_event_cb(scr->cook_back, cook_screen_cook_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_13
    scr->label_13 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_13, "RECIPES");
    lv_label_set_long_mode(scr->label_13, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_13, 168, 28);
    lv_obj_set_size(scr->label_13, 465, 85);
    lv_obj_clear_flag(scr->label_13, LV_OBJ_FLAG_SCROLLABLE);

    // Set style of scr->label_13
    lv_obj_set_style_text_font(scr->label_13, fs_fzltxhjw_95, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_13, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);


}
