/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void __attribute__((weak)) cook_sel_screen_coil_back_custom_clicked(void) {
}

static void cook_sel_screen_coil_back_clicked (lv_event_t *e) {
    cook_sel_screen_coil_back_custom_clicked();
}


void cook_sel_screen_create(ui_manager_t *ui)
{
    cook_sel_screen_t *scr = cook_sel_screen_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->coil_back
    scr->coil_back = lv_img_create(scr->obj);
    lv_img_set_src(scr->coil_back, LVGL_IMAGE_PATH(back_135x135.png));
    lv_img_set_pivot(scr->coil_back, 50, 50);
    lv_img_set_angle(scr->coil_back, 0);
    lv_obj_set_style_img_opa(scr->coil_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->coil_back, 22, 22);
    lv_obj_add_flag(scr->coil_back, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->coil_back
    lv_obj_add_event_cb(scr->coil_back, cook_sel_screen_coil_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_39
    scr->label_39 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_39, "Choose the coil");
    lv_label_set_long_mode(scr->label_39, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_39, 168, 28);
    lv_obj_set_size(scr->label_39, 750, 117);

    // Set style of scr->label_39
    lv_obj_set_style_text_font(scr->label_39, fs_fzltxhjw_95, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_39, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);


}
