/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void __attribute__((weak)) lang_screen_custom_created(void) {
}

void __attribute__((weak)) lang_screen_cn_img_custom_clicked(void) {
}

static void lang_screen_cn_img_clicked (lv_event_t *e) {
    lang_screen_cn_img_custom_clicked();
}

void __attribute__((weak)) lang_screen_lang_back_custom_clicked(void) {
}

static void lang_screen_lang_back_clicked (lv_event_t *e) {
    lang_screen_lang_back_custom_clicked();
}

void __attribute__((weak)) lang_screen_eng_img_custom_clicked(void) {
}

static void lang_screen_eng_img_clicked (lv_event_t *e) {
    lang_screen_eng_img_custom_clicked();
}


void lang_screen_create(ui_manager_t *ui)
{
    lang_screen_t *scr = lang_screen_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cn_img
    scr->cn_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->cn_img, LVGL_IMAGE_PATH(Chinese_450x525.png));
    lv_img_set_pivot(scr->cn_img, 50, 50);
    lv_img_set_angle(scr->cn_img, 0);
    lv_obj_set_style_img_opa(scr->cn_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->cn_img, 485, 172);
    lv_obj_add_flag(scr->cn_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->cn_img
    lv_obj_add_event_cb(scr->cn_img, lang_screen_cn_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->lang_back
    scr->lang_back = lv_img_create(scr->obj);
    lv_img_set_src(scr->lang_back, LVGL_IMAGE_PATH(back_135x135.png));
    lv_img_set_pivot(scr->lang_back, 50, 50);
    lv_img_set_angle(scr->lang_back, 0);
    lv_obj_set_style_img_opa(scr->lang_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->lang_back, 22, 22);
    lv_obj_add_flag(scr->lang_back, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->lang_back
    lv_obj_add_event_cb(scr->lang_back, lang_screen_lang_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->eng_img
    scr->eng_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->eng_img, LVGL_IMAGE_PATH(English_450x525.png));
    lv_img_set_pivot(scr->eng_img, 50, 50);
    lv_img_set_angle(scr->eng_img, 0);
    lv_obj_set_style_img_opa(scr->eng_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->eng_img, 28, 172);
    lv_obj_add_flag(scr->eng_img, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->eng_img
    lv_obj_add_event_cb(scr->eng_img, lang_screen_eng_img_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_6
    scr->label_6 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_6, "LANGUAGE");
    lv_label_set_long_mode(scr->label_6, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6, 168, 26);
    lv_obj_set_size(scr->label_6, 704, 94);

    // Set style of scr->label_6
    lv_obj_set_style_text_font(scr->label_6, fs_fzltxhjw_95, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_6, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(scr->label_6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->eng_label
    scr->eng_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->eng_label, "English");
    lv_label_set_long_mode(scr->eng_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->eng_label, 39, 603);
    lv_obj_set_size(scr->eng_label, 252, 72);
    lv_obj_add_flag(scr->eng_label, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->eng_label, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->eng_label
    lv_obj_set_style_text_font(scr->eng_label, fs_fzltxhjw_70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->eng_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cn_label
    scr->cn_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->cn_label, "Chinese");
    lv_label_set_long_mode(scr->cn_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cn_label, 515, 603);
    lv_obj_set_size(scr->cn_label, 289, 76);
    lv_obj_add_flag(scr->cn_label, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->cn_label, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->cn_label
    lv_obj_set_style_text_font(scr->cn_label, fs_fzltxhjw_70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cn_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    lang_screen_custom_created();
}
