/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void __attribute__((weak)) logo_scr_custom_created(void) {
}


void logo_scr_create(ui_manager_t *ui)
{
    logo_scr_t *scr = logo_scr_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(Logo-background.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->logo_amni
    scr->logo_amni = lv_animimg_create(scr->obj);
    static const char *logo_amni_imgs[10] = {
        LVGL_IMAGE_PATH(LOGO (1).png),
        LVGL_IMAGE_PATH(LOGO (2).png),
        LVGL_IMAGE_PATH(LOGO (3).png),
        LVGL_IMAGE_PATH(LOGO (4).png),
        LVGL_IMAGE_PATH(LOGO (5).png),
        LVGL_IMAGE_PATH(LOGO (6).png),
        LVGL_IMAGE_PATH(LOGO (7).png),
        LVGL_IMAGE_PATH(LOGO (8).png),
        LVGL_IMAGE_PATH(LOGO (9).png),
        LVGL_IMAGE_PATH(LOGO (10).png),
    };

    logo_scr_custom_created();

    
    lv_animimg_set_src(scr->logo_amni, (const void **)logo_amni_imgs, 10);
    lv_animimg_set_duration(scr->logo_amni, 1000);
    lv_animimg_set_repeat_count(scr->logo_amni, 5);
    lv_animimg_start(scr->logo_amni);
    lv_obj_set_pos(scr->logo_amni, 430, 295);
    lv_obj_set_size(scr->logo_amni, 420, 124);

    
}
