/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void __attribute__((weak)) qrcode_screen_qr_back_custom_clicked(void) {
}

static void qrcode_screen_qr_back_clicked (lv_event_t *e) {
    qrcode_screen_qr_back_custom_clicked();
}


void qrcode_screen_create(ui_manager_t *ui)
{
    qrcode_screen_t *scr = qrcode_screen_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->qrcode
    scr->qrcode = lv_img_create(scr->obj);
    lv_img_set_src(scr->qrcode, LVGL_IMAGE_PATH(qr_page.png));
    lv_img_set_pivot(scr->qrcode, 50, 50);
    lv_img_set_angle(scr->qrcode, 0);
    lv_obj_set_style_img_opa(scr->qrcode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->qrcode, 240, 120);

    // Init scr->qr_back
    scr->qr_back = lv_img_create(scr->obj);
    lv_img_set_src(scr->qr_back, LVGL_IMAGE_PATH(back_135x135.png));
    lv_img_set_pivot(scr->qr_back, 50, 50);
    lv_img_set_angle(scr->qr_back, 0);
    lv_obj_set_style_img_opa(scr->qr_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->qr_back, 22, 22);
    lv_obj_add_flag(scr->qr_back, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->qr_back
    lv_obj_add_event_cb(scr->qr_back, qrcode_screen_qr_back_clicked, LV_EVENT_CLICKED, NULL);


}
