/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void screen_2_create(ui_manager_t *ui)
{
    screen_2_t *scr = screen_2_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_5
    scr->image_5 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_5, LVGL_IMAGE_PATH(suspend_300x300.png));
    lv_img_set_pivot(scr->image_5, 50, 50);
    lv_img_set_angle(scr->image_5, 0);
    lv_obj_set_style_img_opa(scr->image_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_5, 490, 210);
    lv_obj_add_flag(scr->image_5, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->line_1
    scr->line_1 = lv_line_create(scr->obj);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t line_1_point[] ={{60, 20}, {240, 20}};
#else
    static lv_point_precise_t line_1_point[] ={{60, 20}, {240, 20}};
#endif
    lv_line_set_points(scr->line_1, line_1_point, 2);
    lv_obj_set_pos(scr->line_1, 490, 9);
    lv_obj_set_size(scr->line_1, 300, 40);
    lv_obj_add_flag(scr->line_1, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->line_1
    lv_obj_set_style_line_color(scr->line_1, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(scr->line_1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(scr->line_1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2
    scr->container_2 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_2, 0, -720);
    lv_obj_set_size(scr->container_2, 1280, 720);
    lv_obj_set_scrollbar_mode(scr->container_2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_2, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->container_2
    lv_obj_set_style_bg_color(scr->container_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_11
    scr->image_11 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_11, LVGL_IMAGE_PATH(merge.png));
    lv_img_set_pivot(scr->image_11, 50, 50);
    lv_img_set_angle(scr->image_11, 0);
    lv_obj_set_style_img_opa(scr->image_11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_11, 21, 24);
    lv_obj_add_flag(scr->image_11, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_12
    scr->image_12 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_12, LVGL_IMAGE_PATH(cook.png));
    lv_img_set_pivot(scr->image_12, 50, 50);
    lv_img_set_angle(scr->image_12, 0);
    lv_obj_set_style_img_opa(scr->image_12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_12, 273, 24);
    lv_obj_add_flag(scr->image_12, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_13
    scr->image_13 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_13, LVGL_IMAGE_PATH(lang.png));
    lv_img_set_pivot(scr->image_13, 50, 50);
    lv_img_set_angle(scr->image_13, 0);
    lv_obj_set_style_img_opa(scr->image_13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_13, 525, 24);
    lv_obj_add_flag(scr->image_13, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_14
    scr->image_14 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_14, LVGL_IMAGE_PATH(qrcode.png));
    lv_img_set_pivot(scr->image_14, 50, 50);
    lv_img_set_angle(scr->image_14, 0);
    lv_obj_set_style_img_opa(scr->image_14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_14, 777, 24);
    lv_obj_add_flag(scr->image_14, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_15
    scr->image_15 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_15, LVGL_IMAGE_PATH(about.png));
    lv_img_set_pivot(scr->image_15, 50, 50);
    lv_img_set_angle(scr->image_15, 0);
    lv_obj_set_style_img_opa(scr->image_15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_15, 1029, 24);
    lv_obj_add_flag(scr->image_15, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->container_3
    scr->container_3 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_3, 875, 366);
    lv_obj_set_size(scr->container_3, 400, 350);
    lv_obj_set_scrollbar_mode(scr->container_3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_3, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_3
    lv_obj_set_style_bg_color(scr->container_3, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->animImg_6
    scr->animImg_6 = lv_animimg_create(scr->container_3);
    static const char *animImg_6_imgs[16] = {
        LVGL_IMAGE_PATH(1_400x345.png),
        LVGL_IMAGE_PATH(2_400x345.png),
        LVGL_IMAGE_PATH(3_400x345.png),
        LVGL_IMAGE_PATH(4_400x345.png),
        LVGL_IMAGE_PATH(5_400x345.png),
        LVGL_IMAGE_PATH(6_400x345.png),
        LVGL_IMAGE_PATH(7_400x345.png),
        LVGL_IMAGE_PATH(8_400x345.png),
        LVGL_IMAGE_PATH(9_400x345.png),
        LVGL_IMAGE_PATH(10_400x345.png),
        LVGL_IMAGE_PATH(11_400x345.png),
        LVGL_IMAGE_PATH(12_400x345.png),
        LVGL_IMAGE_PATH(13_400x345.png),
        LVGL_IMAGE_PATH(14_400x345.png),
        LVGL_IMAGE_PATH(15_400x345.png),
        LVGL_IMAGE_PATH(16_400x345.png),
    };
    lv_animimg_set_src(scr->animImg_6, (const void **)animImg_6_imgs, 16);
    lv_animimg_set_duration(scr->animImg_6, 2000);
    lv_animimg_set_repeat_count(scr->animImg_6, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(scr->animImg_6);
    lv_obj_set_pos(scr->animImg_6, 0, 5);
    lv_obj_set_size(scr->animImg_6, 400, 345);
    lv_obj_add_flag(scr->animImg_6, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->animImg_6, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->line_2
    scr->line_2 = lv_line_create(scr->container_3);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t line_2_point[] ={{0, 0}, {160, 0}};
#else
    static lv_point_precise_t line_2_point[] ={{0, 0}, {160, 0}};
#endif
    lv_line_set_points(scr->line_2, line_2_point, 2);
    lv_obj_set_pos(scr->line_2, 120, 170);
    lv_obj_set_size(scr->line_2, 160, 10);
    lv_obj_add_flag(scr->line_2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->line_2, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->line_2
    lv_obj_set_style_line_color(scr->line_2, lv_color_hex(0xdddddd), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(scr->line_2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_16
    scr->image_16 = lv_img_create(scr->container_3);
    lv_img_set_src(scr->image_16, LVGL_IMAGE_PATH(thermos_150x150.png));
    lv_img_set_pivot(scr->image_16, 50, 50);
    lv_img_set_angle(scr->image_16, 0);
    lv_obj_set_style_img_opa(scr->image_16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_16, 125, 100);
    lv_obj_add_flag(scr->image_16, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_16, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->label_9
    scr->label_9 = lv_label_create(scr->container_3);
    lv_label_set_text(scr->label_9, "4:00");
    lv_label_set_long_mode(scr->label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9, 125, 260);
    lv_obj_set_size(scr->label_9, 150, 50);
    lv_obj_add_flag(scr->label_9, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->label_9, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->label_9
    lv_obj_set_style_text_font(scr->label_9, fs_fzltxhjw_50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_9, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_10
    scr->label_10 = lv_label_create(scr->container_3);
    lv_label_set_text(scr->label_10, "0");
    lv_label_set_long_mode(scr->label_10, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_10, 150, 115);
    lv_obj_set_size(scr->label_10, 100, 120);
    lv_obj_add_flag(scr->label_10, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->label_10, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->label_10, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->label_10
    lv_obj_set_style_text_font(scr->label_10, fs_fzltxhjw_120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_10, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_5
    scr->container_5 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_5, 5, 366);
    lv_obj_set_size(scr->container_5, 400, 350);
    lv_obj_set_scrollbar_mode(scr->container_5, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_5, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_5
    lv_obj_set_style_bg_color(scr->container_5, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->animImg_9
    scr->animImg_9 = lv_animimg_create(scr->container_5);
    static const char *animImg_9_imgs[16] = {
        LVGL_IMAGE_PATH(1_400x345.png),
        LVGL_IMAGE_PATH(2_400x345.png),
        LVGL_IMAGE_PATH(3_400x345.png),
        LVGL_IMAGE_PATH(4_400x345.png),
        LVGL_IMAGE_PATH(5_400x345.png),
        LVGL_IMAGE_PATH(6_400x345.png),
        LVGL_IMAGE_PATH(7_400x345.png),
        LVGL_IMAGE_PATH(8_400x345.png),
        LVGL_IMAGE_PATH(9_400x345.png),
        LVGL_IMAGE_PATH(10_400x345.png),
        LVGL_IMAGE_PATH(11_400x345.png),
        LVGL_IMAGE_PATH(12_400x345.png),
        LVGL_IMAGE_PATH(13_400x345.png),
        LVGL_IMAGE_PATH(14_400x345.png),
        LVGL_IMAGE_PATH(15_400x345.png),
        LVGL_IMAGE_PATH(16_400x345.png),
    };
    lv_animimg_set_src(scr->animImg_9, (const void **)animImg_9_imgs, 16);
    lv_animimg_set_duration(scr->animImg_9, 2000);
    lv_animimg_set_repeat_count(scr->animImg_9, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(scr->animImg_9);
    lv_obj_set_pos(scr->animImg_9, 0, 5);
    lv_obj_set_size(scr->animImg_9, 400, 345);
    lv_obj_add_flag(scr->animImg_9, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->animImg_9, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->line_4
    scr->line_4 = lv_line_create(scr->container_5);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t line_4_point[] ={{0, 0}, {160, 0}};
#else
    static lv_point_precise_t line_4_point[] ={{0, 0}, {160, 0}};
#endif
    lv_line_set_points(scr->line_4, line_4_point, 2);
    lv_obj_set_pos(scr->line_4, 120, 170);
    lv_obj_set_size(scr->line_4, 160, 10);
    lv_obj_add_flag(scr->line_4, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->line_4, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->line_4
    lv_obj_set_style_line_color(scr->line_4, lv_color_hex(0xdddddd), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(scr->line_4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_18
    scr->image_18 = lv_img_create(scr->container_5);
    lv_img_set_src(scr->image_18, LVGL_IMAGE_PATH(thermos_150x150.png));
    lv_img_set_pivot(scr->image_18, 50, 50);
    lv_img_set_angle(scr->image_18, 0);
    lv_obj_set_style_img_opa(scr->image_18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_18, 125, 100);
    lv_obj_add_flag(scr->image_18, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_18, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->label_13
    scr->label_13 = lv_label_create(scr->container_5);
    lv_label_set_text(scr->label_13, "4:00");
    lv_label_set_long_mode(scr->label_13, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_13, 125, 260);
    lv_obj_set_size(scr->label_13, 150, 50);
    lv_obj_add_flag(scr->label_13, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->label_13, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->label_13
    lv_obj_set_style_text_font(scr->label_13, fs_fzltxhjw_50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_13, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_14
    scr->label_14 = lv_label_create(scr->container_5);
    lv_label_set_text(scr->label_14, "0");
    lv_label_set_long_mode(scr->label_14, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_14, 150, 115);
    lv_obj_set_size(scr->label_14, 100, 120);
    lv_obj_add_flag(scr->label_14, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->label_14, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->label_14, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->label_14
    lv_obj_set_style_text_font(scr->label_14, fs_fzltxhjw_120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_14, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_6
    scr->container_6 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_6, 5, 4);
    lv_obj_set_size(scr->container_6, 400, 350);
    lv_obj_set_scrollbar_mode(scr->container_6, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_6, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_6
    lv_obj_set_style_bg_color(scr->container_6, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->animImg_11
    scr->animImg_11 = lv_animimg_create(scr->container_6);
    static const char *animImg_11_imgs[16] = {
        LVGL_IMAGE_PATH(1_400x345.png),
        LVGL_IMAGE_PATH(2_400x345.png),
        LVGL_IMAGE_PATH(3_400x345.png),
        LVGL_IMAGE_PATH(4_400x345.png),
        LVGL_IMAGE_PATH(5_400x345.png),
        LVGL_IMAGE_PATH(6_400x345.png),
        LVGL_IMAGE_PATH(7_400x345.png),
        LVGL_IMAGE_PATH(8_400x345.png),
        LVGL_IMAGE_PATH(9_400x345.png),
        LVGL_IMAGE_PATH(10_400x345.png),
        LVGL_IMAGE_PATH(11_400x345.png),
        LVGL_IMAGE_PATH(12_400x345.png),
        LVGL_IMAGE_PATH(13_400x345.png),
        LVGL_IMAGE_PATH(14_400x345.png),
        LVGL_IMAGE_PATH(15_400x345.png),
        LVGL_IMAGE_PATH(16_400x345.png),
    };
    lv_animimg_set_src(scr->animImg_11, (const void **)animImg_11_imgs, 16);
    lv_animimg_set_duration(scr->animImg_11, 2000);
    lv_animimg_set_repeat_count(scr->animImg_11, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(scr->animImg_11);
    lv_obj_set_pos(scr->animImg_11, 0, 5);
    lv_obj_set_size(scr->animImg_11, 400, 345);
    lv_obj_add_flag(scr->animImg_11, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->animImg_11, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->line_5
    scr->line_5 = lv_line_create(scr->container_6);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t line_5_point[] ={{0, 0}, {160, 0}};
#else
    static lv_point_precise_t line_5_point[] ={{0, 0}, {160, 0}};
#endif
    lv_line_set_points(scr->line_5, line_5_point, 2);
    lv_obj_set_pos(scr->line_5, 120, 170);
    lv_obj_set_size(scr->line_5, 160, 10);
    lv_obj_add_flag(scr->line_5, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->line_5, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->line_5
    lv_obj_set_style_line_color(scr->line_5, lv_color_hex(0xdddddd), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(scr->line_5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_19
    scr->image_19 = lv_img_create(scr->container_6);
    lv_img_set_src(scr->image_19, LVGL_IMAGE_PATH(thermos_150x150.png));
    lv_img_set_pivot(scr->image_19, 50, 50);
    lv_img_set_angle(scr->image_19, 0);
    lv_obj_set_style_img_opa(scr->image_19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_19, 125, 100);
    lv_obj_add_flag(scr->image_19, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_19, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->label_15
    scr->label_15 = lv_label_create(scr->container_6);
    lv_label_set_text(scr->label_15, "4:00");
    lv_label_set_long_mode(scr->label_15, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_15, 125, 260);
    lv_obj_set_size(scr->label_15, 150, 50);
    lv_obj_add_flag(scr->label_15, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->label_15, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->label_15
    lv_obj_set_style_text_font(scr->label_15, fs_fzltxhjw_50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_15, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_15, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_16
    scr->label_16 = lv_label_create(scr->container_6);
    lv_label_set_text(scr->label_16, "0");
    lv_label_set_long_mode(scr->label_16, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_16, 150, 115);
    lv_obj_set_size(scr->label_16, 100, 120);
    lv_obj_add_flag(scr->label_16, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->label_16, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->label_16, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->label_16
    lv_obj_set_style_text_font(scr->label_16, fs_fzltxhjw_120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_16, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_7
    scr->container_7 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_7, 875, 5);
    lv_obj_set_size(scr->container_7, 400, 350);
    lv_obj_set_scrollbar_mode(scr->container_7, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_7, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_7
    lv_obj_set_style_bg_color(scr->container_7, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->animImg_12
    scr->animImg_12 = lv_animimg_create(scr->container_7);
    static const char *animImg_12_imgs[16] = {
        LVGL_IMAGE_PATH(1_400x345.png),
        LVGL_IMAGE_PATH(2_400x345.png),
        LVGL_IMAGE_PATH(3_400x345.png),
        LVGL_IMAGE_PATH(4_400x345.png),
        LVGL_IMAGE_PATH(5_400x345.png),
        LVGL_IMAGE_PATH(6_400x345.png),
        LVGL_IMAGE_PATH(7_400x345.png),
        LVGL_IMAGE_PATH(8_400x345.png),
        LVGL_IMAGE_PATH(9_400x345.png),
        LVGL_IMAGE_PATH(10_400x345.png),
        LVGL_IMAGE_PATH(11_400x345.png),
        LVGL_IMAGE_PATH(12_400x345.png),
        LVGL_IMAGE_PATH(13_400x345.png),
        LVGL_IMAGE_PATH(14_400x345.png),
        LVGL_IMAGE_PATH(15_400x345.png),
        LVGL_IMAGE_PATH(16_400x345.png),
    };
    lv_animimg_set_src(scr->animImg_12, (const void **)animImg_12_imgs, 16);
    lv_animimg_set_duration(scr->animImg_12, 2000);
    lv_animimg_set_repeat_count(scr->animImg_12, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(scr->animImg_12);
    lv_obj_set_pos(scr->animImg_12, 0, 5);
    lv_obj_set_size(scr->animImg_12, 400, 345);
    lv_obj_add_flag(scr->animImg_12, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->animImg_12, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->line_6
    scr->line_6 = lv_line_create(scr->container_7);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t line_6_point[] ={{0, 0}, {160, 0}};
#else
    static lv_point_precise_t line_6_point[] ={{0, 0}, {160, 0}};
#endif
    lv_line_set_points(scr->line_6, line_6_point, 2);
    lv_obj_set_pos(scr->line_6, 120, 170);
    lv_obj_set_size(scr->line_6, 160, 10);
    lv_obj_add_flag(scr->line_6, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->line_6, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->line_6
    lv_obj_set_style_line_color(scr->line_6, lv_color_hex(0xdddddd), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(scr->line_6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_20
    scr->image_20 = lv_img_create(scr->container_7);
    lv_img_set_src(scr->image_20, LVGL_IMAGE_PATH(thermos_150x150.png));
    lv_img_set_pivot(scr->image_20, 50, 50);
    lv_img_set_angle(scr->image_20, 0);
    lv_obj_set_style_img_opa(scr->image_20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_20, 125, 100);
    lv_obj_add_flag(scr->image_20, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_20, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->label_17
    scr->label_17 = lv_label_create(scr->container_7);
    lv_label_set_text(scr->label_17, "4:00");
    lv_label_set_long_mode(scr->label_17, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_17, 125, 260);
    lv_obj_set_size(scr->label_17, 150, 50);
    lv_obj_add_flag(scr->label_17, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->label_17, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->label_17
    lv_obj_set_style_text_font(scr->label_17, fs_fzltxhjw_50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_17, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_18
    scr->label_18 = lv_label_create(scr->container_7);
    lv_label_set_text(scr->label_18, "0");
    lv_label_set_long_mode(scr->label_18, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_18, 150, 115);
    lv_obj_set_size(scr->label_18, 100, 120);
    lv_obj_add_flag(scr->label_18, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->label_18, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->label_18, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Set style of scr->label_18
    lv_obj_set_style_text_font(scr->label_18, fs_fzltxhjw_120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_18, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_18, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}
