/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void __attribute__((weak)) screen_button_1_custom_clicked(void) {
}

static void screen_button_1_clicked (lv_event_t *e) {
    screen_button_1_custom_clicked();
}


void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->switch_1
    scr->switch_1 = lv_switch_create(scr->obj);
    lv_obj_set_pos(scr->switch_1, 345, 555);
    lv_obj_set_size(scr->switch_1, 125, 47);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "Button");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 713, 521);
    lv_obj_set_size(scr->button_1, 184, 104);

    // Set style of scr->button_1
    lv_obj_set_style_text_font(scr->button_1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1
    lv_obj_add_event_cb(scr->button_1, screen_button_1_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_1, "0");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 522, 230);
    lv_obj_set_size(scr->label_1, 174, 43);

    // Set style of scr->label_1
    lv_obj_set_style_text_font(scr->label_1, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}
