/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void __attribute__((weak)) setting_cook_custom_load_start(void) {
}
void __attribute__((weak)) setting_cook_custom_unload_start(void) {
}

static void setting_cook_load_start (lv_event_t *e) {
    setting_cook_custom_load_start();
}

static void setting_cook_unload_start (lv_event_t *e) {
    setting_cook_custom_unload_start();
}

void __attribute__((weak)) setting_cook_back_cont_custom_clicked(void) {
}

static void setting_cook_back_cont_clicked (lv_event_t *e) {
    setting_cook_back_cont_custom_clicked();
}

void __attribute__((weak)) setting_cook_min_label_custom_clicked(void) {
}

static void setting_cook_min_label_clicked (lv_event_t *e) {
    setting_cook_min_label_custom_clicked();
}

void __attribute__((weak)) setting_cook_max_label_custom_clicked(void) {
}

static void setting_cook_max_label_clicked (lv_event_t *e) {
    setting_cook_max_label_custom_clicked();
}

void __attribute__((weak)) setting_cook_thermos_cont_custom_clicked(void) {
}

static void setting_cook_thermos_cont_clicked (lv_event_t *e) {
    setting_cook_thermos_cont_custom_clicked();
}

void __attribute__((weak)) setting_cook_max_gear_cont_custom_clicked(void) {
}

static void setting_cook_max_gear_cont_clicked (lv_event_t *e) {
    setting_cook_max_gear_cont_custom_clicked();
}

void __attribute__((weak)) setting_cook_timing_cont_custom_clicked(void) {
}

static void setting_cook_timing_cont_clicked (lv_event_t *e) {
    setting_cook_timing_cont_custom_clicked();
}

void __attribute__((weak)) setting_cook_gear_slider_custom_value_changed(void) {
}
void __attribute__((weak)) setting_cook_gear_slider_custom_released(void) {
}

static void setting_cook_gear_slider_released (lv_event_t *e) {
    setting_cook_gear_slider_custom_released();
}

static void setting_cook_gear_slider_value_changed (lv_event_t *e) {
    setting_cook_gear_slider_custom_value_changed();
}


void setting_cook_create(ui_manager_t *ui)
{
    setting_cook_t *scr = setting_cook_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, setting_cook_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);
    lv_obj_add_event_cb(scr->obj, setting_cook_unload_start, LV_EVENT_SCREEN_UNLOAD_START, NULL);

    // Init scr->back_cont
    scr->back_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->back_cont, 5, 5);
    lv_obj_set_size(scr->back_cont, 240, 500);
    lv_obj_set_scrollbar_mode(scr->back_cont, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->back_cont, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->back_cont
    lv_obj_set_style_bg_color(scr->back_cont, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->back_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->back_cont, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->back_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->back_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->back_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->back_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->back_cont
    lv_obj_add_event_cb(scr->back_cont, setting_cook_back_cont_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->back_cont);
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_style_img_opa(scr->image_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_3, 70, 190);
    lv_obj_add_flag(scr->image_3, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_3, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->min_label
    scr->min_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->min_label, "0");
    lv_label_set_long_mode(scr->min_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min_label, 30, 525);
    lv_obj_set_size(scr->min_label, 150, 150);
    lv_obj_add_flag(scr->min_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->min_label
    lv_obj_set_style_text_font(scr->min_label, fs_fzltxhjw_150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->min_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->min_label
    lv_obj_add_event_cb(scr->min_label, setting_cook_min_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->max_label
    scr->max_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->max_label, "9");
    lv_label_set_long_mode(scr->max_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->max_label, 1100, 525);
    lv_obj_set_size(scr->max_label, 150, 150);
    lv_obj_add_flag(scr->max_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->max_label
    lv_obj_set_style_text_font(scr->max_label, fs_fzltxhjw_150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->max_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->max_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->max_label
    lv_obj_add_event_cb(scr->max_label, setting_cook_max_label_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->thermos_cont
    scr->thermos_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->thermos_cont, 260, 5);
    lv_obj_set_size(scr->thermos_cont, 240, 500);
    lv_obj_set_scrollbar_mode(scr->thermos_cont, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->thermos_cont, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->thermos_cont
    lv_obj_set_style_bg_color(scr->thermos_cont, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->thermos_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->thermos_cont, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->thermos_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->thermos_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->thermos_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->thermos_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->thermos_cont
    lv_obj_add_event_cb(scr->thermos_cont, setting_cook_thermos_cont_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_4
    scr->image_4 = lv_img_create(scr->thermos_cont);
    lv_img_set_src(scr->image_4, LVGL_IMAGE_PATH(thermos_120x120.png));
    lv_img_set_pivot(scr->image_4, 50, 50);
    lv_img_set_angle(scr->image_4, 0);
    lv_obj_set_style_img_opa(scr->image_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_4, 60, 190);
    lv_obj_add_flag(scr->image_4, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_4, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->max_gear_cont
    scr->max_gear_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->max_gear_cont, 780, 5);
    lv_obj_set_size(scr->max_gear_cont, 240, 500);
    lv_obj_set_scrollbar_mode(scr->max_gear_cont, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->max_gear_cont, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->max_gear_cont
    lv_obj_set_style_bg_color(scr->max_gear_cont, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->max_gear_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->max_gear_cont, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->max_gear_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->max_gear_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->max_gear_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->max_gear_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->max_gear_cont
    lv_obj_add_event_cb(scr->max_gear_cont, setting_cook_max_gear_cont_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_5
    scr->image_5 = lv_img_create(scr->max_gear_cont);
    lv_img_set_src(scr->image_5, LVGL_IMAGE_PATH(max_gear_120x120.png));
    lv_img_set_pivot(scr->image_5, 50, 50);
    lv_img_set_angle(scr->image_5, 0);
    lv_obj_set_style_img_opa(scr->image_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_5, 60, 190);
    lv_obj_add_flag(scr->image_5, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_5, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->timing_cont
    scr->timing_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->timing_cont, 1035, 5);
    lv_obj_set_size(scr->timing_cont, 240, 500);
    lv_obj_set_scrollbar_mode(scr->timing_cont, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->timing_cont, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->timing_cont
    lv_obj_set_style_bg_color(scr->timing_cont, lv_color_hex(0x2e3235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->timing_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->timing_cont, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->timing_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->timing_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->timing_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->timing_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->timing_cont
    lv_obj_add_event_cb(scr->timing_cont, setting_cook_timing_cont_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_6
    scr->image_6 = lv_img_create(scr->timing_cont);
    lv_img_set_src(scr->image_6, LVGL_IMAGE_PATH(timing_120x120.png));
    lv_img_set_pivot(scr->image_6, 50, 50);
    lv_img_set_angle(scr->image_6, 0);
    lv_obj_set_style_img_opa(scr->image_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_6, 60, 185);
    lv_obj_add_flag(scr->image_6, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->image_6, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Init scr->gear_label
    scr->gear_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->gear_label, "0");
    lv_label_set_long_mode(scr->gear_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->gear_label, 565, 135);
    lv_obj_set_size(scr->gear_label, 150, 250);

    // Set style of scr->gear_label
    lv_obj_set_style_text_font(scr->gear_label, fs_fzltxhjw_250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->gear_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->gear_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->gear_slider
    scr->gear_slider = lv_slider_create(scr->obj);
    lv_slider_set_range(scr->gear_slider, 0, 9);
    lv_slider_set_value(scr->gear_slider, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->gear_slider, 215, 540);
    lv_obj_set_size(scr->gear_slider, 850, 120);

    // Set style of scr->gear_slider
    lv_obj_set_style_bg_color(scr->gear_slider, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->gear_slider, lv_color_hex(0xff7900), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->gear_slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Set event handler of scr->gear_slider
    lv_obj_add_event_cb(scr->gear_slider, setting_cook_gear_slider_released, LV_EVENT_RELEASED, NULL);
    lv_obj_add_event_cb(scr->gear_slider, setting_cook_gear_slider_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Init scr->func_label
    scr->func_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->func_label, "Heating Temperature\nStill");
    lv_label_set_long_mode(scr->func_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->func_label, 0, 540);
    lv_obj_set_size(scr->func_label, 1280, 150);
    lv_obj_add_flag(scr->func_label, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->func_label
    lv_obj_set_style_text_font(scr->func_label, fs_fzltxhjw_75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->func_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->func_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}
