/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

static void main_screen_line_2_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create drop_screen
        drop_screen_create(&ui_manager);
        // load drop_screen
        lv_scr_load_anim(drop_screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 200, 0, true);
    }
}


void main_screen_create(ui_manager_t *ui)
{
    main_screen_t *scr = main_screen_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->obj, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->line_2
    scr->line_2 = lv_line_create(scr->obj);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t line_2_point[] ={{0, 0}, {100, 0}};
#else
    static lv_point_precise_t line_2_point[] ={{0, 0}, {100, 0}};
#endif
    lv_line_set_points(scr->line_2, line_2_point, 2);
    lv_obj_set_pos(scr->line_2, 588, 13);
    lv_obj_set_size(scr->line_2, 103, 5);
    lv_obj_add_flag(scr->line_2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->line_2, LV_OBJ_FLAG_GESTURE_BUBBLE);

    // Set style of scr->line_2
    lv_obj_set_style_bg_color(scr->line_2, lv_color_hex(0x616161), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(scr->line_2, lv_color_hex(0x616161), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(scr->line_2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(scr->line_2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->line_2
    lv_obj_add_event_cb(scr->line_2, main_screen_line_2_clicked, LV_EVENT_CLICKED, NULL);


}
