/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *line_2;
} main_screen_t;

typedef struct {
    lv_obj_t *obj;
} drop_screen_t;


typedef struct {
    bool auto_del;
    main_screen_t main_screen;
    drop_screen_t drop_screen;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline main_screen_t *main_screen_get(ui_manager_t *ui)
{
    return &ui->main_screen;
}

static inline drop_screen_t *drop_screen_get(ui_manager_t *ui)
{
    return &ui->drop_screen;
}


void main_screen_create(ui_manager_t *ui);
void drop_screen_create(ui_manager_t *ui);



extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
